language: julia
os:
  - linux
# - osx #too slow
julia:
  - 0.4
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.clone("https://github.com/DataWookie/PhysicalConstants.jl"); Pkg.build("Blackbody"); Pkg.test("Blackbody"; coverage=true)';
#after_success:
#  - julia -e 'cd(Pkg.dir("Example")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
#  - julia -e 'cd(Pkg.dir("Example")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())';
